-- GENERATED BY scripts/generate-seed.mjs - do not edit by hand.
-- Edit data/checklist.json and run `npm run seed:build` instead.
--
-- Re-running this file is safe: it upserts buildings/areas/tasks and never
-- touches task_log, activity, maintenance or users.

-- St George
INSERT INTO buildings (name, sort_order) VALUES ('St George', 0)
  ON CONFLICT(name) DO UPDATE SET sort_order = excluded.sort_order, active = 1;
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'St George'), 'Bathrooms', 0)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Toilet', 'Clean including behind toilet cistern (no bugs/ants)', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Toilet');
UPDATE tasks SET description = 'Clean including behind toilet cistern (no bugs/ants)', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Toilet';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Toilet brush', 'Clean off any bugs, dirt and grime', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Toilet brush');
UPDATE tasks SET description = 'Clean off any bugs, dirt and grime', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Toilet brush';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Sanitary bin', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Sanitary bin');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Sanitary bin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Urinal (boys)', 'Clean, scrub and replace tablets', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)');
UPDATE tasks SET description = 'Clean, scrub and replace tablets', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Paper towel / litter', 'Pick up from floor and surfaces', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter');
UPDATE tasks SET description = 'Pick up from floor and surfaces', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Shower cubicle', 'Wipe down surfaces and remove bugs', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Shower cubicle');
UPDATE tasks SET description = 'Wipe down surfaces and remove bugs', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Shower cubicle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Mirror', 'Wipe with glass cleaner - no streaks', 6
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Mirror');
UPDATE tasks SET description = 'Wipe with glass cleaner - no streaks', sort_order = 6, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Mirror';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Surfaces', 'Wipe vanity and sills', 7
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Surfaces');
UPDATE tasks SET description = 'Wipe vanity and sills', sort_order = 7, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Surfaces';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Basin', 'Clean tapware and basin thoroughly', 8
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Basin');
UPDATE tasks SET description = 'Clean tapware and basin thoroughly', sort_order = 8, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Basin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Toilet paper / paper towel / soap', 'Top up', 9
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap');
UPDATE tasks SET description = 'Top up', sort_order = 9, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Bins', 'Empty, wipe over and replace liners', 10
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 10, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Bins';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Toilet / shower area', 'Clear any cobwebs', 11
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area');
UPDATE tasks SET description = 'Clear any cobwebs', sort_order = 11, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms'), 'Floors', 'Mop all, including shower cubicles, check drains', 12
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Floors');
UPDATE tasks SET description = 'Mop all, including shower cubicles, check drains', sort_order = 12, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Bathrooms') AND item = 'Floors';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'St George'), 'Shelter', 1)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter'), 'Microwave', 'Check empty and clean', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Microwave');
UPDATE tasks SET description = 'Check empty and clean', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Microwave';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter'), 'Kettle', 'Wipe over and clean', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Kettle');
UPDATE tasks SET description = 'Wipe over and clean', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Kettle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter'), 'Kitchen surfaces and sink', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter'), 'Soap', 'Refill soap / detergent', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Soap');
UPDATE tasks SET description = 'Refill soap / detergent', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter'), 'Supplies', '1 x dish cloth, 1 x green scourer, 1 x metal scourer', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Supplies');
UPDATE tasks SET description = '1 x dish cloth, 1 x green scourer, 1 x metal scourer', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Supplies';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter'), 'Bins', 'Empty, wipe over and replace liners', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Shelter') AND item = 'Bins';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'St George'), 'Every visit', 2)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit'), 'Litter', 'Check for and pick up any litter', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit') AND item = 'Litter');
UPDATE tasks SET description = 'Check for and pick up any litter', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit') AND item = 'Litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit'), 'BBQ', 'Check BBQ is clean - report to Maintenance if not', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit') AND item = 'BBQ');
UPDATE tasks SET description = 'Check BBQ is clean - report to Maintenance if not', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit') AND item = 'BBQ';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit'), 'Lost property', 'Deliver to Reception with a note of where it was found and the date', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit') AND item = 'Lost property');
UPDATE tasks SET description = 'Deliver to Reception with a note of where it was found and the date', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit') AND item = 'Lost property';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit'), 'Damage', 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit') AND item = 'Damage');
UPDATE tasks SET description = 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'St George' AND a.name = 'Every visit') AND item = 'Damage';

-- Gilwell
INSERT INTO buildings (name, sort_order) VALUES ('Gilwell', 1)
  ON CONFLICT(name) DO UPDATE SET sort_order = excluded.sort_order, active = 1;
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Gilwell'), 'Bathrooms', 0)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Toilet', 'Clean including behind toilet cistern (no bugs/ants)', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Toilet');
UPDATE tasks SET description = 'Clean including behind toilet cistern (no bugs/ants)', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Toilet';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Toilet brush', 'Clean off any bugs, dirt and grime', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Toilet brush');
UPDATE tasks SET description = 'Clean off any bugs, dirt and grime', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Toilet brush';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Sanitary bin', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Sanitary bin');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Sanitary bin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Urinal (boys)', 'Clean, scrub and replace tablets', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)');
UPDATE tasks SET description = 'Clean, scrub and replace tablets', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Paper towel / litter', 'Pick up from floor and surfaces', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter');
UPDATE tasks SET description = 'Pick up from floor and surfaces', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Shower cubicle', 'Wipe down surfaces and remove bugs', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Shower cubicle');
UPDATE tasks SET description = 'Wipe down surfaces and remove bugs', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Shower cubicle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Mirror', 'Wipe with glass cleaner - no streaks', 6
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Mirror');
UPDATE tasks SET description = 'Wipe with glass cleaner - no streaks', sort_order = 6, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Mirror';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Surfaces', 'Wipe vanity and sills', 7
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Surfaces');
UPDATE tasks SET description = 'Wipe vanity and sills', sort_order = 7, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Surfaces';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Basin', 'Clean tapware and basin thoroughly', 8
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Basin');
UPDATE tasks SET description = 'Clean tapware and basin thoroughly', sort_order = 8, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Basin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Toilet paper / paper towel / soap', 'Top up', 9
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap');
UPDATE tasks SET description = 'Top up', sort_order = 9, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Bins', 'Empty, wipe over and replace liners', 10
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 10, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Bins';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Toilet / shower area', 'Clear any cobwebs', 11
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area');
UPDATE tasks SET description = 'Clear any cobwebs', sort_order = 11, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms'), 'Floors', 'Mop all, including shower cubicles, check drains', 12
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Floors');
UPDATE tasks SET description = 'Mop all, including shower cubicles, check drains', sort_order = 12, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Bathrooms') AND item = 'Floors';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Gilwell'), 'Shelter', 1)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter'), 'Microwave', 'Check empty and clean', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Microwave');
UPDATE tasks SET description = 'Check empty and clean', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Microwave';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter'), 'Kettle', 'Wipe over and clean', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Kettle');
UPDATE tasks SET description = 'Wipe over and clean', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Kettle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter'), 'Kitchen surfaces and sink', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter'), 'Soap', 'Refill soap / detergent', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Soap');
UPDATE tasks SET description = 'Refill soap / detergent', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter'), 'Supplies', '1 x dish cloth, 1 x green scourer, 1 x metal scourer', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Supplies');
UPDATE tasks SET description = '1 x dish cloth, 1 x green scourer, 1 x metal scourer', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Supplies';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter'), 'Bins', 'Empty, wipe over and replace liners', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Shelter') AND item = 'Bins';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Gilwell'), 'Every visit', 2)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit'), 'Litter', 'Check for and pick up any litter', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit') AND item = 'Litter');
UPDATE tasks SET description = 'Check for and pick up any litter', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit') AND item = 'Litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit'), 'BBQ', 'Check BBQ is clean - report to Maintenance if not', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit') AND item = 'BBQ');
UPDATE tasks SET description = 'Check BBQ is clean - report to Maintenance if not', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit') AND item = 'BBQ';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit'), 'Lost property', 'Deliver to Reception with a note of where it was found and the date', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit') AND item = 'Lost property');
UPDATE tasks SET description = 'Deliver to Reception with a note of where it was found and the date', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit') AND item = 'Lost property';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit'), 'Damage', 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit') AND item = 'Damage');
UPDATE tasks SET description = 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Gilwell' AND a.name = 'Every visit') AND item = 'Damage';

-- Brownsea
INSERT INTO buildings (name, sort_order) VALUES ('Brownsea', 2)
  ON CONFLICT(name) DO UPDATE SET sort_order = excluded.sort_order, active = 1;
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Brownsea'), 'Bathrooms', 0)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Toilet', 'Clean including behind toilet cistern (no bugs/ants)', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Toilet');
UPDATE tasks SET description = 'Clean including behind toilet cistern (no bugs/ants)', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Toilet';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Toilet brush', 'Clean off any bugs, dirt and grime', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Toilet brush');
UPDATE tasks SET description = 'Clean off any bugs, dirt and grime', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Toilet brush';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Sanitary bin', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Sanitary bin');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Sanitary bin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Urinal (boys)', 'Clean, scrub and replace tablets', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)');
UPDATE tasks SET description = 'Clean, scrub and replace tablets', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Paper towel / litter', 'Pick up from floor and surfaces', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter');
UPDATE tasks SET description = 'Pick up from floor and surfaces', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Shower cubicle', 'Wipe down surfaces and remove bugs', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Shower cubicle');
UPDATE tasks SET description = 'Wipe down surfaces and remove bugs', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Shower cubicle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Mirror', 'Wipe with glass cleaner - no streaks', 6
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Mirror');
UPDATE tasks SET description = 'Wipe with glass cleaner - no streaks', sort_order = 6, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Mirror';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Surfaces', 'Wipe vanity and sills', 7
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Surfaces');
UPDATE tasks SET description = 'Wipe vanity and sills', sort_order = 7, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Surfaces';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Basin', 'Clean tapware and basin thoroughly', 8
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Basin');
UPDATE tasks SET description = 'Clean tapware and basin thoroughly', sort_order = 8, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Basin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Toilet paper / paper towel / soap', 'Top up', 9
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap');
UPDATE tasks SET description = 'Top up', sort_order = 9, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Bins', 'Empty, wipe over and replace liners', 10
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 10, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Bins';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Toilet / shower area', 'Clear any cobwebs', 11
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area');
UPDATE tasks SET description = 'Clear any cobwebs', sort_order = 11, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms'), 'Floors', 'Mop all, including shower cubicles, check drains', 12
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Floors');
UPDATE tasks SET description = 'Mop all, including shower cubicles, check drains', sort_order = 12, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Bathrooms') AND item = 'Floors';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Brownsea'), 'Shelter', 1)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter'), 'Microwave', 'Check empty and clean', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Microwave');
UPDATE tasks SET description = 'Check empty and clean', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Microwave';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter'), 'Kettle', 'Wipe over and clean', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Kettle');
UPDATE tasks SET description = 'Wipe over and clean', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Kettle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter'), 'Kitchen surfaces and sink', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter'), 'Soap', 'Refill soap / detergent', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Soap');
UPDATE tasks SET description = 'Refill soap / detergent', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter'), 'Supplies', '1 x dish cloth, 1 x green scourer, 1 x metal scourer', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Supplies');
UPDATE tasks SET description = '1 x dish cloth, 1 x green scourer, 1 x metal scourer', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Supplies';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter'), 'Bins', 'Empty, wipe over and replace liners', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Shelter') AND item = 'Bins';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Brownsea'), 'Every visit', 2)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit'), 'Litter', 'Check for and pick up any litter', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit') AND item = 'Litter');
UPDATE tasks SET description = 'Check for and pick up any litter', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit') AND item = 'Litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit'), 'BBQ', 'Check BBQ is clean - report to Maintenance if not', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit') AND item = 'BBQ');
UPDATE tasks SET description = 'Check BBQ is clean - report to Maintenance if not', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit') AND item = 'BBQ';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit'), 'Lost property', 'Deliver to Reception with a note of where it was found and the date', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit') AND item = 'Lost property');
UPDATE tasks SET description = 'Deliver to Reception with a note of where it was found and the date', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit') AND item = 'Lost property';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit'), 'Damage', 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit') AND item = 'Damage');
UPDATE tasks SET description = 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Every visit') AND item = 'Damage';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Brownsea'), 'Brownsea specific', 3)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific'), 'Fridge', 'Check fridge is empty and clean', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific') AND item = 'Fridge');
UPDATE tasks SET description = 'Check fridge is empty and clean', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific') AND item = 'Fridge';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific'), 'Small bins', 'Empty and replace liners in small bins inside shelter, including BBQ', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific') AND item = 'Small bins');
UPDATE tasks SET description = 'Empty and replace liners in small bins inside shelter, including BBQ', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific') AND item = 'Small bins';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific'), 'BBQ', 'Check if BBQ needs cleaning and report to office', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific') AND item = 'BBQ');
UPDATE tasks SET description = 'Check if BBQ needs cleaning and report to office', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Brownsea' AND a.name = 'Brownsea specific') AND item = 'BBQ';

-- Lone's Hut
INSERT INTO buildings (name, sort_order) VALUES ('Lone''s Hut', 3)
  ON CONFLICT(name) DO UPDATE SET sort_order = excluded.sort_order, active = 1;
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Lone''s Hut'), 'Bathrooms', 0)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Toilet', 'Clean including behind toilet cistern (no bugs/ants)', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Toilet');
UPDATE tasks SET description = 'Clean including behind toilet cistern (no bugs/ants)', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Toilet';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Toilet brush', 'Clean off any bugs, dirt and grime', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Toilet brush');
UPDATE tasks SET description = 'Clean off any bugs, dirt and grime', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Toilet brush';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Sanitary bin', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Sanitary bin');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Sanitary bin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Urinal (boys)', 'Clean, scrub and replace tablets', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)');
UPDATE tasks SET description = 'Clean, scrub and replace tablets', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Paper towel / litter', 'Pick up from floor and surfaces', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter');
UPDATE tasks SET description = 'Pick up from floor and surfaces', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Shower cubicle', 'Wipe down surfaces and remove bugs', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Shower cubicle');
UPDATE tasks SET description = 'Wipe down surfaces and remove bugs', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Shower cubicle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Mirror', 'Wipe with glass cleaner - no streaks', 6
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Mirror');
UPDATE tasks SET description = 'Wipe with glass cleaner - no streaks', sort_order = 6, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Mirror';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Surfaces', 'Wipe vanity and sills', 7
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Surfaces');
UPDATE tasks SET description = 'Wipe vanity and sills', sort_order = 7, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Surfaces';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Basin', 'Clean tapware and basin thoroughly', 8
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Basin');
UPDATE tasks SET description = 'Clean tapware and basin thoroughly', sort_order = 8, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Basin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Toilet paper / paper towel / soap', 'Top up', 9
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap');
UPDATE tasks SET description = 'Top up', sort_order = 9, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Bins', 'Empty, wipe over and replace liners', 10
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 10, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Bins';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Toilet / shower area', 'Clear any cobwebs', 11
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area');
UPDATE tasks SET description = 'Clear any cobwebs', sort_order = 11, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms'), 'Floors', 'Mop all, including shower cubicles, check drains', 12
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Floors');
UPDATE tasks SET description = 'Mop all, including shower cubicles, check drains', sort_order = 12, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Bathrooms') AND item = 'Floors';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Lone''s Hut'), 'Shelter', 1)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter'), 'Microwave', 'Check empty and clean', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Microwave');
UPDATE tasks SET description = 'Check empty and clean', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Microwave';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter'), 'Kettle', 'Wipe over and clean', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Kettle');
UPDATE tasks SET description = 'Wipe over and clean', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Kettle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter'), 'Kitchen surfaces and sink', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter'), 'Soap', 'Refill soap / detergent', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Soap');
UPDATE tasks SET description = 'Refill soap / detergent', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter'), 'Supplies', '1 x dish cloth, 1 x green scourer, 1 x metal scourer', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Supplies');
UPDATE tasks SET description = '1 x dish cloth, 1 x green scourer, 1 x metal scourer', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Supplies';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter'), 'Bins', 'Empty, wipe over and replace liners', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Shelter') AND item = 'Bins';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Lone''s Hut'), 'Every visit', 2)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit'), 'Litter', 'Check for and pick up any litter', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit') AND item = 'Litter');
UPDATE tasks SET description = 'Check for and pick up any litter', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit') AND item = 'Litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit'), 'BBQ', 'Check BBQ is clean - report to Maintenance if not', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit') AND item = 'BBQ');
UPDATE tasks SET description = 'Check BBQ is clean - report to Maintenance if not', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit') AND item = 'BBQ';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit'), 'Lost property', 'Deliver to Reception with a note of where it was found and the date', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit') AND item = 'Lost property');
UPDATE tasks SET description = 'Deliver to Reception with a note of where it was found and the date', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit') AND item = 'Lost property';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit'), 'Damage', 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit') AND item = 'Damage');
UPDATE tasks SET description = 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Lone''s Hut' AND a.name = 'Every visit') AND item = 'Damage';

-- Bert's Bog
INSERT INTO buildings (name, sort_order) VALUES ('Bert''s Bog', 4)
  ON CONFLICT(name) DO UPDATE SET sort_order = excluded.sort_order, active = 1;
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Bert''s Bog'), 'Bathrooms', 0)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Toilet', 'Clean including behind toilet cistern (no bugs/ants)', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Toilet');
UPDATE tasks SET description = 'Clean including behind toilet cistern (no bugs/ants)', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Toilet';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Toilet brush', 'Clean off any bugs, dirt and grime', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Toilet brush');
UPDATE tasks SET description = 'Clean off any bugs, dirt and grime', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Toilet brush';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Sanitary bin', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Sanitary bin');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Sanitary bin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Urinal (boys)', 'Clean, scrub and replace tablets', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)');
UPDATE tasks SET description = 'Clean, scrub and replace tablets', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Urinal (boys)';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Paper towel / litter', 'Pick up from floor and surfaces', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter');
UPDATE tasks SET description = 'Pick up from floor and surfaces', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Paper towel / litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Shower cubicle', 'Wipe down surfaces and remove bugs', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Shower cubicle');
UPDATE tasks SET description = 'Wipe down surfaces and remove bugs', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Shower cubicle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Mirror', 'Wipe with glass cleaner - no streaks', 6
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Mirror');
UPDATE tasks SET description = 'Wipe with glass cleaner - no streaks', sort_order = 6, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Mirror';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Surfaces', 'Wipe vanity and sills', 7
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Surfaces');
UPDATE tasks SET description = 'Wipe vanity and sills', sort_order = 7, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Surfaces';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Basin', 'Clean tapware and basin thoroughly', 8
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Basin');
UPDATE tasks SET description = 'Clean tapware and basin thoroughly', sort_order = 8, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Basin';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Toilet paper / paper towel / soap', 'Top up', 9
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap');
UPDATE tasks SET description = 'Top up', sort_order = 9, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Toilet paper / paper towel / soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Bins', 'Empty, wipe over and replace liners', 10
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 10, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Bins';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Toilet / shower area', 'Clear any cobwebs', 11
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area');
UPDATE tasks SET description = 'Clear any cobwebs', sort_order = 11, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Toilet / shower area';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms'), 'Floors', 'Mop all, including shower cubicles, check drains', 12
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Floors');
UPDATE tasks SET description = 'Mop all, including shower cubicles, check drains', sort_order = 12, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Bathrooms') AND item = 'Floors';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Bert''s Bog'), 'Shelter', 1)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter'), 'Microwave', 'Check empty and clean', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Microwave');
UPDATE tasks SET description = 'Check empty and clean', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Microwave';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter'), 'Kettle', 'Wipe over and clean', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Kettle');
UPDATE tasks SET description = 'Wipe over and clean', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Kettle';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter'), 'Kitchen surfaces and sink', 'Wiped over and clean', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink');
UPDATE tasks SET description = 'Wiped over and clean', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Kitchen surfaces and sink';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter'), 'Soap', 'Refill soap / detergent', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Soap');
UPDATE tasks SET description = 'Refill soap / detergent', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Soap';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter'), 'Supplies', '1 x dish cloth, 1 x green scourer, 1 x metal scourer', 4
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Supplies');
UPDATE tasks SET description = '1 x dish cloth, 1 x green scourer, 1 x metal scourer', sort_order = 4, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Supplies';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter'), 'Bins', 'Empty, wipe over and replace liners', 5
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Bins');
UPDATE tasks SET description = 'Empty, wipe over and replace liners', sort_order = 5, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Shelter') AND item = 'Bins';
INSERT INTO areas (building_id, name, sort_order) VALUES ((SELECT id FROM buildings WHERE name = 'Bert''s Bog'), 'Every visit', 2)
  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit'), 'Litter', 'Check for and pick up any litter', 0
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit') AND item = 'Litter');
UPDATE tasks SET description = 'Check for and pick up any litter', sort_order = 0, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit') AND item = 'Litter';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit'), 'BBQ', 'Check BBQ is clean - report to Maintenance if not', 1
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit') AND item = 'BBQ');
UPDATE tasks SET description = 'Check BBQ is clean - report to Maintenance if not', sort_order = 1, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit') AND item = 'BBQ';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit'), 'Lost property', 'Deliver to Reception with a note of where it was found and the date', 2
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit') AND item = 'Lost property');
UPDATE tasks SET description = 'Deliver to Reception with a note of where it was found and the date', sort_order = 2, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit') AND item = 'Lost property';
INSERT INTO tasks (area_id, item, description, sort_order)
  SELECT (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit'), 'Damage', 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', 3
  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit') AND item = 'Damage');
UPDATE tasks SET description = 'Report any maintenance or damage (broken fittings, graffiti etc) with photos', sort_order = 3, active = 1
  WHERE area_id = (SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id WHERE b.name = 'Bert''s Bog' AND a.name = 'Every visit') AND item = 'Damage';
