#!/usr/bin/env node
// Turns data/checklist.json into seed.sql.
// Re-run after editing the checklist: npm run seed:build

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cfg = JSON.parse(readFileSync(join(root, 'data/checklist.json'), 'utf8'));

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

const lines = [
  '-- GENERATED BY scripts/generate-seed.mjs - do not edit by hand.',
  '-- Edit data/checklist.json and run `npm run seed:build` instead.',
  '--',
  '-- Re-running this file is safe: it upserts buildings/areas/tasks and never',
  '-- touches task_log, activity, maintenance or users.',
  '',
];

// Every building gets the shared areas; a building may append extra ones.
const sharedNames = Object.keys(cfg.sharedAreas);

cfg.buildings.forEach((building, bIndex) => {
  const areas = [
    ...sharedNames.map((name) => ({ name, tasks: cfg.sharedAreas[name] })),
    ...(building.areas ?? []),
  ];

  lines.push(`-- ${building.name}`);
  lines.push(
    `INSERT INTO buildings (name, sort_order) VALUES (${q(building.name)}, ${bIndex})`,
    `  ON CONFLICT(name) DO UPDATE SET sort_order = excluded.sort_order, active = 1;`,
  );

  areas.forEach((area, aIndex) => {
    const b = `(SELECT id FROM buildings WHERE name = ${q(building.name)})`;
    lines.push(
      `INSERT INTO areas (building_id, name, sort_order) VALUES (${b}, ${q(area.name)}, ${aIndex})`,
      `  ON CONFLICT(building_id, name) DO UPDATE SET sort_order = excluded.sort_order;`,
    );

    const a = `(SELECT a.id FROM areas a JOIN buildings b ON b.id = a.building_id` +
      ` WHERE b.name = ${q(building.name)} AND a.name = ${q(area.name)})`;

    area.tasks.forEach(([item, description], tIndex) => {
      // Matched on (area, item) so re-seeding edits wording in place and keeps history.
      lines.push(
        `INSERT INTO tasks (area_id, item, description, sort_order)`,
        `  SELECT ${a}, ${q(item)}, ${q(description)}, ${tIndex}`,
        `  WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE area_id = ${a} AND item = ${q(item)});`,
        `UPDATE tasks SET description = ${q(description)}, sort_order = ${tIndex}, active = 1`,
        `  WHERE area_id = ${a} AND item = ${q(item)};`,
      );
    });
  });
  lines.push('');
});

writeFileSync(join(root, 'seed.sql'), lines.join('\n'));

const areaCount = cfg.buildings.length * sharedNames.length +
  cfg.buildings.reduce((n, b) => n + (b.areas?.length ?? 0), 0);
console.log(`seed.sql written: ${cfg.buildings.length} buildings, ${areaCount} areas.`);
